export const config = [
  {
    type: "Background",
    options: ["ETH", "MATIC", "ARB"],
  },
  {
    type: "Mane",
    options: ["Orange", "Pink", "Yellow", "Blue", "Grey", "Black"],
  },
  {
    type: "Face",
    options: [
      "Orange",
      "OrangeGrin",
      "OrangeGrowl",
      "OrangeBleah",
      "Blue",
      "BlueGrin",
      "BlueGrowl",
      "BlueBleah",
      "Pink",
      "PinkGrin",
      "PinkGrowl",
      "PinkBleah",
      "SalmonPink",
      "SalmonPinkGrin",
      "SalmonPinkGrowl",
      "SalmonPinkBleah",
      "robot",
    ],
  },
  {
    type: "Hats",
    options: [
      "HeadphoneBlack",
      "HeadphoneBlue",
      "Horn",
      "Crown",
      "PartyHat",
      "MoshHat",
      "HatRed",
      "HatBlack",
      "Propeller",
      "Propeller2",
      "GoldPiercing",
      "BluePiercing",
      "Army",
      "Doctor",
      "Beanie",
      "Bucket",
    ],
  },
  {
    type: "Sunglasses",
    options: [
      "Pixel",
      "Sports1",
      "Sports2",
      "Black",
      "Blue",
      "VR",
      "3D",
      "Laser",
    ],
  },
  {
    type: "Clothes",
    options: [
      "Army",
      "Hiphop",
      "Mosh",
      "Macintosh",
      "Trippy",
      "Cursor",
      "Doctor",
    ],
  },
  {
    type: "Text",
    options: [
      "LoveAtFirstSight",
      "TropicalJuice",
      "ZettaiRyoiki",
      "EscapeFromReality",
      "InholeTheFuture",
      "TokyoSummer",
      "SushiParadice",
      "Cucumber",
    ],
  },
];
